name: "test"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - name: Install and test
        run: |
          nix develop --command bash -c "nix build .#posts_test_dna -o workdir/posts_test.dna && RUST_LOG=holochain::core::workflow=info DNA_PATH=../../../workdir/posts_test.dna cargo test --profile release"

